### ISSUE TITLE
Link to paper

### ISSUE THREAD

**Issue by RichardShea** [IdeasLabUT/WSDM-2022-Challenge#1]
Hi, Is there a link to the paper?  I've tried searching google, but can't find it. 

Thank you,

-Richard

**Comment by kevin-s-xu** [comment]
We didn't write a paper on this. On both datasets, we fit a CHIP model to the entire network (ignoring edge types). Then, for any node pair (i, j) and time interval (s, t), we compute the expected number of edges and rescale it to form the feature for that node pair and time interval. On dataset A, we also compute some additional features based on the node and edge type features.
